package yh.hotplugin.system.integration;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.noear.solon.Solon;
import org.noear.solon.core.handle.Context;
import yh.hotplugin.security.api.SecurityPrincipal;
import yh.hotplugin.security.tenant.*;
import yh.hotplugin.system.application.SystemPermissionProvider;
import yh.hotplugin.system.infrastructure.*;
import yh.hotplugin.system.infrastructure.mybatis.*;

import java.io.InputStream;
import java.math.BigDecimal;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;

/** SaaS lifecycle, plans, usage, rate policies, backup and operations APIs. */
final class SaasHttpApi {
    static final String[] ROUTES = {
            "/system/tenant/{id}/lifecycle", "/system/tenant/{id}/deleteRetry", "/system/tenant/{id}/deleteCancel", "/system/tenant/deleted",
            "/system/saas/plans", "/system/saas/plan", "/system/saas/plan/{id}", "/system/saas/plan/{id}/copy", "/system/saas/plan/{id}/publish", "/system/saas/plan/{id}/status", "/system/saas/plan/{id}/versions", "/system/saas/plan/compare", "/system/saas/quotaCatalog", "/system/saas/tenant/{id}/subscription",
            "/system/saas/tenant/{id}/subscription/preview", "/system/saas/tenant/{id}/subscription/pending", "/system/saas/tenant/{id}/subscription/history",
            "/system/saas/tenant/{id}/usage", "/system/tenant/currentUsage", "/system/saas/overview", "/system/saas/tenant/{id}/quotaOverrides",
            "/system/saas/tenant/{id}/usage/calibrate", "/system/saas/tenant/{id}/ratePolicies", "/system/saas/tenant/{id}/ratePolicy", "/system/saas/ratePolicy/{id}", "/system/saas/tenant/{id}/rateEvents", "/system/saas/tenant/{id}/rateStatistics",
            "/system/saas/tenant/{id}/backups", "/system/saas/tenant/{id}/backup", "/system/saas/tenant/{id}/backup/{backupId}",
            "/system/saas/tenant/{id}/backup/{backupId}/download", "/system/saas/tenant/{id}/backup/{backupId}/restore", "/system/saas/tenant/{id}/restoreTask/{taskId}", "/system/saas/tenant/{id}/restoreTask/{taskId}/retry"
    };
    private final ObjectMapper json;
    private final MybatisExecutor db;
    private final TenantLifecycleTaskService tasks;
    private final SystemPermissionProvider provider;
    private final TenantBackupService backups;
    private final TenantUsageCalibrationService usageCalibration;
    private ScheduledExecutorService subscriptionScheduler;

    SaasHttpApi(ObjectMapper json, JdbcAuthorizationRepository authorization, JdbcManagementRepository management,
                TenantLifecycleTaskService tasks, SystemPermissionProvider provider, String backupDirectory) {
        this.json=json; this.db=authorization.executor(); this.tasks=tasks; this.provider=provider;
        this.usageCalibration=new TenantUsageCalibrationService(authorization);
        this.backups=new TenantBackupService(authorization,backupDirectory,usageCalibration,provider);
    }

    void register() {
        Solon.app().router().get("/system/tenant/{id}/lifecycle",c->guard(c,()->lifecycle(c)));
        Solon.app().router().post("/system/tenant/{id}/deleteRetry",c->guard(c,()->retry(c)));
        Solon.app().router().post("/system/tenant/{id}/deleteCancel",c->guard(c,()->cancel(c)));
        Solon.app().router().get("/system/tenant/deleted",c->guard(c,()->{platform(c,"system:tenant:list");render(c,tasks.deletedTenants());}));
        Solon.app().router().get("/system/saas/plans",c->guard(c,()->plans(c)));
        Solon.app().router().post("/system/saas/plan",c->guard(c,()->savePlan(c,false)));
        Solon.app().router().put("/system/saas/plan",c->guard(c,()->savePlan(c,true)));
        Solon.app().router().delete("/system/saas/plan/{id}",c->guard(c,()->deletePlan(c)));
        Solon.app().router().get("/system/saas/plan/compare",c->guard(c,()->comparePlans(c)));
        Solon.app().router().get("/system/saas/quotaCatalog",c->guard(c,()->quotaCatalog(c)));
        Solon.app().router().get("/system/saas/plan/{id}",c->guard(c,()->planDetail(c)));
        Solon.app().router().post("/system/saas/plan/{id}/copy",c->guard(c,()->copyPlan(c)));
        Solon.app().router().post("/system/saas/plan/{id}/publish",c->guard(c,()->publishPlan(c)));
        Solon.app().router().put("/system/saas/plan/{id}/status",c->guard(c,()->changePlanStatus(c)));
        Solon.app().router().get("/system/saas/plan/{id}/versions",c->guard(c,()->planVersions(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/subscription",c->guard(c,()->subscription(c)));
        Solon.app().router().put("/system/saas/tenant/{id}/subscription",c->guard(c,()->changeSubscription(c)));
        Solon.app().router().post("/system/saas/tenant/{id}/subscription/preview",c->guard(c,()->subscriptionPreview(c)));
        Solon.app().router().delete("/system/saas/tenant/{id}/subscription/pending",c->guard(c,()->cancelPendingSubscription(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/subscription/history",c->guard(c,()->subscriptionHistory(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/usage",c->guard(c,()->usage(c,tenantId(c))));
        Solon.app().router().get("/system/tenant/currentUsage",c->guard(c,()->usage(c,principal(c).getTenantId())));
        Solon.app().router().put("/system/saas/tenant/{id}/quotaOverrides",c->guard(c,()->saveQuotaOverrides(c)));
        Solon.app().router().post("/system/saas/tenant/{id}/usage/calibrate",c->guard(c,()->calibrateUsage(c)));
        Solon.app().router().get("/system/saas/overview",c->guard(c,()->overview(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/ratePolicies",c->guard(c,()->ratePolicies(c)));
        Solon.app().router().put("/system/saas/tenant/{id}/ratePolicy",c->guard(c,()->saveRatePolicy(c)));
        Solon.app().router().delete("/system/saas/ratePolicy/{id}",c->guard(c,()->deleteRatePolicy(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/rateEvents",c->guard(c,()->rateEvents(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/rateStatistics",c->guard(c,()->rateStatistics(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/backups",c->guard(c,()->listBackups(c)));
        Solon.app().router().post("/system/saas/tenant/{id}/backup",c->guard(c,()->createBackup(c)));
        Solon.app().router().delete("/system/saas/tenant/{id}/backup/{backupId}",c->guard(c,()->deleteBackup(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/backup/{backupId}/download",c->guard(c,()->download(c)));
        Solon.app().router().post("/system/saas/tenant/{id}/backup/{backupId}/restore",c->guard(c,()->restore(c)));
        Solon.app().router().get("/system/saas/tenant/{id}/restoreTask/{taskId}",c->guard(c,()->restoreTask(c)));
        Solon.app().router().post("/system/saas/tenant/{id}/restoreTask/{taskId}/retry",c->guard(c,()->retryRestore(c)));
        subscriptionScheduler=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"pluginSystem-plan-scheduler");t.setDaemon(true);return t;});
        subscriptionScheduler.scheduleWithFixedDelay(()->{try(TenantContext.Scope ignored=TenantContext.openPlatform(0,"pluginSystem.scheduler")){for(Map<String,Object>r:db.query("SELECT tenant_id FROM sys_tenant_subscription WHERE status='ACTIVE' AND pending_plan_id IS NOT NULL AND pending_effective_time<=CURRENT_TIMESTAMP",Collections.<Object>emptyList()))applyDueSubscription(((Number)r.get("tenantId")).longValue());}catch(Throwable e){System.err.println("[pluginSystem] scheduled subscription activation failed: "+e.getMessage());}},1,1,TimeUnit.MINUTES);
        subscriptionScheduler.scheduleWithFixedDelay(()->{try(TenantContext.Scope ignored=TenantContext.openPlatform(0,"pluginSystem.usage.scheduler")){for(Map<String,Object>r:db.query("SELECT id FROM sys_tenant WHERE status='0'",Collections.<Object>emptyList()))try{usageCalibration.calibrate(((Number)r.get("id")).longValue());}catch(Throwable tenantError){System.err.println("[pluginSystem] tenant usage calibration failed: "+tenantError.getMessage());}}catch(Throwable e){System.err.println("[pluginSystem] scheduled usage calibration failed: "+e.getMessage());}},5,30,TimeUnit.MINUTES);
    }

    void close(){if(subscriptionScheduler!=null){subscriptionScheduler.shutdownNow();subscriptionScheduler=null;}}

    private void lifecycle(Context c)throws Throwable{platform(c,"system:tenant:query");Map<String,Object> v=tasks.status(tenantId(c));if(v==null){c.status(404);throw new IllegalArgumentException("租户不存在");}render(c,v);}
    private void retry(Context c)throws Throwable{SecurityPrincipal p=platform(c,"system:tenant:remove");long task=tasks.retry(tenantId(c),p.getUsername());render(c,Collections.singletonMap("taskId",task));}
    private void cancel(Context c)throws Throwable{platform(c,"system:tenant:remove");if(!tasks.cancel(tenantId(c)))throw new IllegalArgumentException("任务已开始清理，不能取消");render(c,null);}

    private void plans(Context c)throws Throwable{
        platform(c,"system:plan:list");
        StringBuilder sql=new StringBuilder("SELECT p.*,(SELECT COUNT(*) FROM sys_tenant_subscription s WHERE s.plan_id=p.id AND s.status='ACTIVE') tenant_count FROM sys_plan p WHERE 1=1");
        List<Object>a=new ArrayList<Object>();
        if(has(c,"planName")){sql.append(" AND p.plan_name LIKE ?");a.add("%"+c.param("planName")+"%");}
        if(has(c,"planCode")){sql.append(" AND p.plan_code LIKE ?");a.add("%"+c.param("planCode")+"%");}
        if(has(c,"lifecycleStatus")){sql.append(" AND p.lifecycle_status=?");a.add(c.param("lifecycleStatus"));}
        if(has(c,"billingCycle")){sql.append(" AND p.billing_cycle=?");a.add(c.param("billingCycle"));}
        sql.append(" ORDER BY p.sort_order,p.plan_code,p.version DESC");
        List<Map<String,Object>>rows=db.query(sql.toString(),a);for(Map<String,Object>p:rows)hydratePlan(p);render(c,rows);
    }
    private void planDetail(Context c)throws Throwable{platform(c,"system:plan:query");Map<String,Object>p=requiredPlan(planId(c));hydratePlan(p);render(c,p);}
    private void savePlan(Context c,boolean update)throws Throwable{
        platform(c,update?"system:plan:edit":"system:plan:add");Map<String,Object>b=body(c);validatePlan(b);final long id;
        if(update){id=num(b.get("id"));Map<String,Object>old=requiredPlan(id);if(!"DRAFT".equals(old.get("lifecycleStatus")))throw new IllegalArgumentException("已发布套餐不可直接修改，请复制为新版本");}
        else{id=0;}
        Long saved=db.transaction(m->{long plan=id;if(update){m.update("UPDATE sys_plan SET plan_name=?,plan_code=?,description=?,display_price=?,currency=?,billing_cycle=?,trial_days=?,sort_order=?,update_time=CURRENT_TIMESTAMP WHERE id=?",Arrays.<Object>asList(text(b,"planName"),text(b,"planCode"),text(b,"description"),decimal(b.get("displayPrice")),defaultText(b,"currency","CNY"),defaultText(b,"billingCycle","MONTH"),intValue(b.get("trialDays"),0),intValue(b.get("sortOrder"),0),plan));}else{int version=intValue(b.get("version"),nextVersion(text(b,"planCode")));plan=txInsert(m,"INSERT INTO sys_plan(plan_name,plan_code,version,status,lifecycle_status,description,is_default,display_price,currency,billing_cycle,trial_days,sort_order,update_time) VALUES(?,?,?,'0','DRAFT',?,'N',?,?,?,?,?,CURRENT_TIMESTAMP)",Arrays.<Object>asList(text(b,"planName"),text(b,"planCode"),version,text(b,"description"),decimal(b.get("displayPrice")),defaultText(b,"currency","CNY"),defaultText(b,"billingCycle","MONTH"),intValue(b.get("trialDays"),0),intValue(b.get("sortOrder"),0)));}m.update("DELETE FROM sys_plan_quota WHERE plan_id=?",Collections.<Object>singletonList(plan));m.update("DELETE FROM sys_plan_feature WHERE plan_id=?",Collections.<Object>singletonList(plan));saveQuotas(m,plan,b.get("quotaDefinitions")!=null?b.get("quotaDefinitions"):b.get("quotas"));saveFeatures(m,plan,b.get("features"));return plan;});
        render(c,Collections.singletonMap("id",saved));
    }
    private void copyPlan(Context c)throws Throwable{platform(c,"system:plan:add");long source=planId(c);Map<String,Object>old=requiredPlan(source);long id=db.transaction(m->{int version=nextVersion(String.valueOf(old.get("planCode")));long target=txInsert(m,"INSERT INTO sys_plan(plan_name,plan_code,version,status,lifecycle_status,description,is_default,display_price,currency,billing_cycle,trial_days,sort_order,update_time) SELECT plan_name,plan_code,?,'0','DRAFT',description,'N',display_price,currency,billing_cycle,trial_days,sort_order,CURRENT_TIMESTAMP FROM sys_plan WHERE id=?",Arrays.<Object>asList(version,source));m.update("INSERT INTO sys_plan_quota(plan_id,quota_key,quota_limit,quota_name,unit,description,category,unlimited) SELECT ?,quota_key,quota_limit,quota_name,unit,description,category,unlimited FROM sys_plan_quota WHERE plan_id=?",Arrays.<Object>asList(target,source));m.update("INSERT INTO sys_plan_feature(plan_id,feature_key,feature_name,enabled,description) SELECT ?,feature_key,feature_name,enabled,description FROM sys_plan_feature WHERE plan_id=?",Arrays.<Object>asList(target,source));return target;});render(c,Collections.singletonMap("id",id));}
    private void publishPlan(Context c)throws Throwable{platform(c,"system:plan:publish");long id=planId(c);Map<String,Object>b=bodyOrEmpty(c);Map<String,Object>p=requiredPlan(id);if(!"DRAFT".equals(p.get("lifecycleStatus")))throw new IllegalArgumentException("只有草稿可以发布");if(db.count("SELECT COUNT(*) FROM sys_plan_quota WHERE plan_id=?",Collections.<Object>singletonList(id))==0)throw new IllegalArgumentException("套餐至少需要一项配额");boolean makeDefault=bool(b.get("isDefault"));db.transaction(m->{if(makeDefault)m.update("UPDATE sys_plan SET is_default='N'",Collections.<Object>emptyList());m.update("UPDATE sys_plan SET lifecycle_status='PUBLISHED',status='0',is_default=?,publish_time=CURRENT_TIMESTAMP,update_time=CURRENT_TIMESTAMP WHERE id=?",Arrays.<Object>asList(makeDefault?"Y":"N",id));return null;});render(c,null);}
    private void changePlanStatus(Context c)throws Throwable{platform(c,"system:plan:publish");long id=planId(c);String status=defaultText(body(c),"lifecycleStatus","DISABLED");if(!Arrays.asList("DISABLED","ARCHIVED").contains(status))throw new IllegalArgumentException("不支持的套餐状态");Map<String,Object>p=requiredPlan(id);if("Y".equals(p.get("isDefault")))throw new IllegalArgumentException("默认套餐不能停用或归档");db.update("UPDATE sys_plan SET lifecycle_status=?,status='1',update_time=CURRENT_TIMESTAMP WHERE id=?",Arrays.<Object>asList(status,id));render(c,null);}
    private void deletePlan(Context c)throws Throwable{platform(c,"system:plan:remove");long id=planId(c);Map<String,Object>p=requiredPlan(id);if(!"DRAFT".equals(p.get("lifecycleStatus")))throw new IllegalArgumentException("只能删除草稿套餐");db.transaction(m->{m.update("DELETE FROM sys_plan_feature WHERE plan_id=?",Collections.<Object>singletonList(id));m.update("DELETE FROM sys_plan_quota WHERE plan_id=?",Collections.<Object>singletonList(id));m.update("DELETE FROM sys_plan WHERE id=?",Collections.<Object>singletonList(id));return null;});render(c,null);}
    private void planVersions(Context c)throws Throwable{platform(c,"system:plan:query");Map<String,Object>p=requiredPlan(planId(c));render(c,db.query("SELECT id,plan_name,plan_code,version,lifecycle_status,publish_time FROM sys_plan WHERE plan_code=? ORDER BY version DESC",Collections.<Object>singletonList(p.get("planCode"))));}
    private void comparePlans(Context c)throws Throwable{platform(c,"system:plan:query");Map<String,Object>out=new LinkedHashMap<String,Object>();Map<String,Object>from=requiredPlan(Long.parseLong(c.param("fromId"))),to=requiredPlan(Long.parseLong(c.param("toId")));hydratePlan(from);hydratePlan(to);out.put("from",from);out.put("to",to);render(c,out);}
    private void quotaCatalog(Context c)throws Throwable{principal(c);render(c,quotaCatalogRows());}
    private void subscription(Context c)throws Throwable{platform(c,"system:tenant:subscription");applyDueSubscription(tenantId(c));render(c,subscriptionData(tenantId(c)));}
    private void subscriptionPreview(Context c)throws Throwable{platform(c,"system:tenant:subscription");long tenant=tenantId(c);Map<String,Object>b=body(c);Map<String,Object>target=publishedPlan(num(b.get("planId")));Map<String,Object>out=new LinkedHashMap<String,Object>();out.put("current",subscriptionData(tenant));hydratePlan(target);out.put("target",target);out.put("overLimit",overLimit(tenant,target));render(c,out);}
    private void changeSubscription(Context c)throws Throwable{SecurityPrincipal p=platform(c,"system:tenant:subscription");long tenant=tenantId(c);Map<String,Object>b=body(c);long plan=num(b.get("planId"));Map<String,Object>target=publishedPlan(plan);Map<String,Object>old=db.one("SELECT s.*,p.version FROM sys_tenant_subscription s JOIN sys_plan p ON p.id=s.plan_id WHERE s.tenant_id=? AND s.status='ACTIVE' ORDER BY s.id DESC LIMIT 1",Collections.<Object>singletonList(tenant));if(old!=null&&num(old.get("planId"))==plan)throw new IllegalArgumentException("租户已订阅相同套餐版本");String mode=defaultText(b,"effectiveMode","IMMEDIATE");if("AT_EXPIRY".equals(mode)){if(old==null||old.get("endTime")==null)throw new IllegalArgumentException("当前订阅没有到期时间，不能选择到期生效");db.transaction(m->{m.update("UPDATE sys_tenant_subscription SET pending_plan_id=?,pending_effective_time=end_time WHERE id=?",Arrays.<Object>asList(plan,old.get("id")));m.update("INSERT INTO sys_tenant_plan_change(tenant_id,old_plan_id,new_plan_id,old_plan_version,new_plan_version,changed_by,remark,effective_mode,scheduled_time,execution_status) VALUES(?,?,?,?,?,?,?,?,?,'PENDING')",Arrays.<Object>asList(tenant,old.get("planId"),plan,old.get("version"),target.get("version"),p.getUsername(),text(b,"remark"),mode,old.get("endTime")));return null;});}else{activateSubscription(tenant,plan,b.get("endTime"),p.getUsername(),text(b,"remark"),old,target);usageCalibration.calibrate(tenant);}render(c,null);}
    private void cancelPendingSubscription(Context c)throws Throwable{SecurityPrincipal p=platform(c,"system:tenant:subscription");long tenant=tenantId(c);db.transaction(m->{m.update("UPDATE sys_tenant_subscription SET pending_plan_id=NULL,pending_effective_time=NULL WHERE tenant_id=? AND status='ACTIVE'",Collections.<Object>singletonList(tenant));m.update("UPDATE sys_tenant_plan_change SET execution_status='CANCELLED' WHERE tenant_id=? AND execution_status='PENDING'",Collections.<Object>singletonList(tenant));return null;});render(c,null);}
    private void subscriptionHistory(Context c)throws Throwable{platform(c,"system:tenant:subscription");render(c,db.query("SELECT pc.*,op.plan_name old_plan_name,np.plan_name new_plan_name FROM sys_tenant_plan_change pc LEFT JOIN sys_plan op ON op.id=pc.old_plan_id JOIN sys_plan np ON np.id=pc.new_plan_id WHERE pc.tenant_id=? ORDER BY pc.id DESC",Collections.<Object>singletonList(tenantId(c))));}

    private void usage(Context c,long tenant)throws Throwable{SecurityPrincipal p=principal(c);if(tenant!=p.getTenantId())platform(c,"platform:manage");applyDueSubscription(tenant);Map<String,Object>out=new LinkedHashMap<String,Object>();Map<String,Long>values=new LinkedHashMap<String,Long>();for(TenantQuotaContributor contributor:TenantContributorRegistry.quota())for(Map.Entry<String,Long>e:contributor.currentUsage(tenant).entrySet())values.put(e.getKey(),e.getValue());Map<String,Object>subscription=subscriptionData(tenant);List<Map<String,Object>>overrides=db.query("SELECT quota_key,quota_limit FROM sys_tenant_quota_override WHERE tenant_id=?",Collections.<Object>singletonList(tenant));Map<String,Long>overrideMap=new HashMap<String,Long>();for(Map<String,Object>q:overrides)overrideMap.put(String.valueOf(q.get("quotaKey")),((Number)q.get("quotaLimit")).longValue());List<Map<String,Object>>quotaRows=new ArrayList<Map<String,Object>>();Map<String,Long>quotas=new LinkedHashMap<String,Long>();if(subscription!=null){for(Map<String,Object>q:(List<Map<String,Object>>)subscription.get("quotaDefinitions")){String key=String.valueOf(q.get("quotaKey"));long base=((Number)q.get("quotaLimit")).longValue(),effective=overrideMap.containsKey(key)?overrideMap.get(key):base,used=values.containsKey(key)?values.get(key):0;Map<String,Object>row=new LinkedHashMap<String,Object>(q);row.put("planLimit",base);row.put("overrideLimit",overrideMap.get(key));row.put("effectiveLimit",effective);row.put("used",used);row.put("usagePercent",effective<=0?0:Math.min(100,Math.round(used*100.0/effective)));row.put("unlimited",effective<0||"Y".equals(q.get("unlimited")));quotaRows.add(row);quotas.put(key,effective);}subscription.put("quotas",quotas);}out.put("usage",values);out.put("subscription",subscription);out.put("overrides",overrides);out.put("quotaRows",quotaRows);render(c,out);}
    @SuppressWarnings("unchecked")private void saveQuotaOverrides(Context c)throws Throwable{SecurityPrincipal p=platform(c,"system:tenant:subscription");long tenant=tenantId(c);Map<String,Object>b=body(c);Object raw=b.get("quotas");if(!(raw instanceof Map)&&!(raw instanceof List))throw new IllegalArgumentException("quotas 必须为对象或结构化数组");Map<String,Object>sub=db.one("SELECT plan_id FROM sys_tenant_subscription WHERE tenant_id=? AND status='ACTIVE' ORDER BY id DESC LIMIT 1",Collections.<Object>singletonList(tenant));if(sub==null)throw new IllegalStateException("TENANT_SUBSCRIPTION_MISSING");Object plan=sub.get("planId");Map<String,Long>values=new LinkedHashMap<String,Long>();if(raw instanceof Map)for(Map.Entry<?,?>e:((Map<?,?>)raw).entrySet())values.put(String.valueOf(e.getKey()),num(e.getValue()));else for(Object x:(List<?>)raw){if(!(x instanceof Map))continue;Map<String,Object>q=(Map<String,Object>)x;if(bool(q.get("override"))||q.get("quotaLimit")!=null)values.put(text(q,"quotaKey"),bool(q.get("unlimited"))?-1:num(q.get("quotaLimit")));}Set<String>allowed=new HashSet<String>();for(Map<String,Object>x:quotaCatalogRows())allowed.add(String.valueOf(x.get("quotaKey")));for(String key:values.keySet())if(!allowed.contains(key))throw new IllegalArgumentException("未知配额项："+key);db.transaction(m->{m.update("DELETE FROM sys_tenant_quota_override WHERE tenant_id=?",Collections.<Object>singletonList(tenant));for(Map.Entry<String,Long>e:values.entrySet())m.update("INSERT INTO sys_tenant_quota_override(tenant_id,quota_key,quota_limit) VALUES(?,?,?)",Arrays.<Object>asList(tenant,e.getKey(),e.getValue()));m.update("INSERT INTO sys_tenant_plan_change(tenant_id,old_plan_id,new_plan_id,changed_by,remark,effective_mode,execution_status) VALUES(?,?,?,?,?,'IMMEDIATE','SUCCEEDED')",Arrays.<Object>asList(tenant,plan,plan,p.getUsername(),"配额覆盖已更新"));return null;});usageCalibration.calibrate(tenant);render(c,null);}
    private void overview(Context c)throws Throwable{platform(c,"platform:manage");Map<String,Object>o=new LinkedHashMap<String,Object>();o.put("tenants",db.one("SELECT COUNT(*) total,SUM(status='0') active,SUM(status='1') disabled FROM sys_tenant",Collections.<Object>emptyList()));o.put("lifecycle",db.query("SELECT lifecycle_status,COUNT(*) count FROM sys_tenant_lifecycle GROUP BY lifecycle_status",Collections.<Object>emptyList()));o.put("plans",db.query("SELECT p.plan_name,COUNT(s.id) tenant_count FROM sys_plan p LEFT JOIN sys_tenant_subscription s ON s.plan_id=p.id AND s.status='ACTIVE' GROUP BY p.id,p.plan_name",Collections.<Object>emptyList()));o.put("expiring",db.query("SELECT id,tenant_name,expire_time FROM sys_tenant WHERE status='0' AND expire_time BETWEEN CURRENT_TIMESTAMP AND DATE_ADD(CURRENT_TIMESTAMP,INTERVAL 30 DAY) ORDER BY expire_time",Collections.<Object>emptyList()));o.put("failedTasks",db.query("SELECT * FROM sys_tenant_lifecycle_task WHERE status IN ('FAILED','WAITING_PLUGIN') ORDER BY id DESC LIMIT 20",Collections.<Object>emptyList()));render(c,o);}

    private void ratePolicies(Context c)throws Throwable{platform(c,"system:tenant:rate:list");render(c,db.query("SELECT * FROM sys_tenant_rate_policy WHERE tenant_id=? ORDER BY id",Collections.<Object>singletonList(tenantId(c))));}
    private void saveRatePolicy(Context c)throws Throwable{platform(c,"system:tenant:rate:edit");long tenant=tenantId(c);Map<String,Object>b=body(c);String route=text(b,"routePattern").trim();if(route.isEmpty())throw new IllegalArgumentException("路由表达式不能为空");if(!route.startsWith("/")&&!"*".equals(route))throw new IllegalArgumentException("路由表达式必须以 / 开始或使用 *");Long minute=nullableLimit(b.get("minuteLimit")),day=nullableLimit(b.get("dayLimit"));String status=defaultText(b,"status","0");if(!"0".equals(status)&&!"1".equals(status))throw new IllegalArgumentException("限流策略状态无效");db.update("INSERT INTO sys_tenant_rate_policy(tenant_id,route_pattern,minute_limit,day_limit,status,update_time) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE minute_limit=VALUES(minute_limit),day_limit=VALUES(day_limit),status=VALUES(status),update_time=CURRENT_TIMESTAMP",Arrays.<Object>asList(tenant,route,minute,day,status));render(c,null);}
    private void deleteRatePolicy(Context c)throws Throwable{platform(c,"system:tenant:rate:edit");db.update("DELETE FROM sys_tenant_rate_policy WHERE id=?",Collections.<Object>singletonList(path(c,"/system/saas/ratePolicy/{id}","id")));render(c,null);}
    private void rateEvents(Context c)throws Throwable{SecurityPrincipal p=principal(c);long tenant=tenantId(c);if(p.getTenantId()!=tenant)platform(c,"system:tenant:rate:list");StringBuilder sql=new StringBuilder("SELECT * FROM sys_tenant_limit_event WHERE tenant_id=?");List<Object>a=new ArrayList<Object>();a.add(tenant);if(has(c,"path")){sql.append(" AND request_path LIKE ?");a.add("%"+c.param("path")+"%");}if(has(c,"startTime")){sql.append(" AND create_time>=?");a.add(c.param("startTime"));}if(has(c,"endTime")){sql.append(" AND create_time<=?");a.add(c.param("endTime"));}sql.append(" ORDER BY id DESC LIMIT 200");render(c,db.query(sql.toString(),a));}
    private void rateStatistics(Context c)throws Throwable{SecurityPrincipal p=principal(c);long tenant=tenantId(c);if(p.getTenantId()!=tenant)platform(c,"system:tenant:rate:list");render(c,db.query("SELECT quota_key,request_path,COUNT(*) event_count,MAX(current_value) peak_value,MAX(create_time) last_event_time FROM sys_tenant_limit_event WHERE tenant_id=? GROUP BY quota_key,request_path ORDER BY event_count DESC LIMIT 100",Collections.<Object>singletonList(tenant)));}
    private void calibrateUsage(Context c)throws Throwable{platform(c,"system:tenant:usage:calibrate");render(c,usageCalibration.calibrate(tenantId(c)));}

    private void listBackups(Context c)throws Throwable{platform(c,"system:tenant:backup:list");render(c,backups.list(tenantId(c)));}
    private void createBackup(Context c)throws Throwable{SecurityPrincipal p=platform(c,"system:tenant:backup:create");render(c,backups.create(tenantId(c),p.getUsername()));}
    private void deleteBackup(Context c)throws Throwable{platform(c,"system:tenant:backup:create");backups.delete(tenantId(c),backupId(c));render(c,null);}
    private void restore(Context c)throws Throwable{SecurityPrincipal p=platform(c,"system:tenant:backup:restore");render(c,backups.restore(tenantId(c),backupId(c),p.getUsername()));}
    private void restoreTask(Context c)throws Throwable{platform(c,"system:tenant:backup:list");Map<String,Object>task=backups.task(taskId(c));if(task==null||num(task.get("tenantId"))!=tenantId(c))throw new IllegalArgumentException("恢复任务不存在");render(c,task);}
    private void retryRestore(Context c)throws Throwable{SecurityPrincipal p=platform(c,"system:tenant:backup:restore");render(c,backups.retry(tenantId(c),taskId(c),p.getUsername()));}
    private void download(Context c)throws Throwable{platform(c,"system:tenant:backup:download");Path file=backups.file(tenantId(c),backupId(c));c.contentType("application/zip");c.headerSet("Content-Disposition","attachment; filename=\""+file.getFileName()+"\"");try(InputStream in=Files.newInputStream(file)){c.output(in);}}

    private void hydratePlan(Map<String,Object>p){Object id=p.get("id");p.put("quotaDefinitions",db.query("SELECT quota_key,quota_limit,COALESCE(quota_name,quota_key) quota_name,unit,description,category,unlimited,(SELECT COUNT(*) FROM sys_tenant_quota_override o WHERE o.quota_key=sys_plan_quota.quota_key) override_count FROM sys_plan_quota WHERE plan_id=? ORDER BY category,quota_key",Collections.<Object>singletonList(id)));p.put("quotas",p.get("quotaDefinitions"));p.put("features",db.query("SELECT feature_key,feature_name,enabled,description FROM sys_plan_feature WHERE plan_id=? ORDER BY feature_key",Collections.<Object>singletonList(id)));}
    private Map<String,Object>requiredPlan(long id){Map<String,Object>p=db.one("SELECT * FROM sys_plan WHERE id=?",Collections.<Object>singletonList(id));if(p==null)throw new IllegalArgumentException("套餐不存在");return p;}
    private Map<String,Object>publishedPlan(long id){Map<String,Object>p=requiredPlan(id);if(!"PUBLISHED".equals(p.get("lifecycleStatus"))||!"0".equals(String.valueOf(p.get("status"))))throw new IllegalArgumentException("只能订阅已发布且启用的套餐");return p;}
    private void validatePlan(Map<String,Object>b){if(text(b,"planName").trim().isEmpty())throw new IllegalArgumentException("套餐名称不能为空");if(!text(b,"planCode").matches("[A-Za-z][A-Za-z0-9_-]{1,63}"))throw new IllegalArgumentException("套餐编码须以字母开头，仅支持字母、数字、下划线和横线");if(decimal(b.get("displayPrice")).compareTo(BigDecimal.ZERO)<0)throw new IllegalArgumentException("展示价格不能小于 0");}
    private int nextVersion(String code){return (int)db.count("SELECT COALESCE(MAX(version),0)+1 FROM sys_plan WHERE plan_code=?",Collections.<Object>singletonList(code));}
    private static long txInsert(DynamicSqlMapper m,String sql,List<Object>a){Map<String,Object>key=new HashMap<String,Object>();m.insert(sql,a,key);return ((Number)key.get("id")).longValue();}
    @SuppressWarnings("unchecked")private void saveQuotas(DynamicSqlMapper m,long plan,Object raw){
        if(raw instanceof Map){for(Map.Entry<?,?>e:((Map<?,?>)raw).entrySet())m.update("INSERT INTO sys_plan_quota(plan_id,quota_key,quota_limit,quota_name,unlimited) VALUES(?,?,?,?,?)",Arrays.<Object>asList(plan,String.valueOf(e.getKey()),num(e.getValue()),String.valueOf(e.getKey()),"N"));return;}
        if(!(raw instanceof List))return;Set<String>catalog=new HashSet<String>();for(Map<String,Object>x:quotaCatalogRows())catalog.add(String.valueOf(x.get("quotaKey")));
        for(Object item:(List<?>)raw){if(!(item instanceof Map))continue;Map<String,Object>q=(Map<String,Object>)item;String key=text(q,"quotaKey");if(!catalog.contains(key))throw new IllegalArgumentException("未知配额项："+key);boolean unlimited=bool(q.get("unlimited"));long limit=unlimited?-1:num(q.get("quotaLimit"));if(!unlimited&&limit<0)throw new IllegalArgumentException("配额不能小于 0："+key);m.update("INSERT INTO sys_plan_quota(plan_id,quota_key,quota_limit,quota_name,unit,description,category,unlimited) VALUES(?,?,?,?,?,?,?,?)",Arrays.<Object>asList(plan,key,limit,text(q,"quotaName"),text(q,"unit"),text(q,"description"),text(q,"category"),unlimited?"Y":"N"));}
    }
    @SuppressWarnings("unchecked")private void saveFeatures(DynamicSqlMapper m,long plan,Object raw){if(!(raw instanceof List))return;for(Object item:(List<?>)raw){if(!(item instanceof Map))continue;Map<String,Object>f=(Map<String,Object>)item;String key=text(f,"featureKey");if(key.trim().isEmpty())throw new IllegalArgumentException("权益编码不能为空");m.update("INSERT INTO sys_plan_feature(plan_id,feature_key,feature_name,enabled,description) VALUES(?,?,?,?,?)",Arrays.<Object>asList(plan,key,text(f,"featureName"),bool(f.get("enabled"))?"Y":"N",text(f,"description")));}}
    private static List<Map<String,Object>>quotaCatalogRows(){String[][]a={{"users.max","用户数量","个","账号资源","允许创建的用户总数"},{"roles.max","角色数量","个","账号资源","允许创建的角色总数"},{"departments.max","部门数量","个","账号资源","允许创建的部门总数"},{"notices.max","公告数量","条","内容资源","允许保留的公告总数"},{"dicts.max","字典数量","项","内容资源","允许创建的字典类型总数"},{"configs.max","参数数量","项","内容资源","允许创建的参数总数"},{"api.minute","每分钟 API 请求","次/分钟","接口资源","租户每分钟请求上限"},{"api.day","每日 API 请求","次/日","接口资源","租户每日请求上限"},{"backups.max","备份保留数量","份","数据保护","允许保留的租户备份数量"}};List<Map<String,Object>>r=new ArrayList<Map<String,Object>>();for(String[]x:a){Map<String,Object>m=new LinkedHashMap<String,Object>();m.put("quotaKey",x[0]);m.put("quotaName",x[1]);m.put("unit",x[2]);m.put("category",x[3]);m.put("description",x[4]);r.add(m);}return r;}
    private Map<String,Object>subscriptionData(long tenant){Map<String,Object>s=db.one("SELECT s.*,p.plan_name,p.plan_code,p.version,p.lifecycle_status,p.display_price,p.currency,p.billing_cycle,pp.plan_name pending_plan_name,pp.version pending_plan_version FROM sys_tenant_subscription s JOIN sys_plan p ON p.id=s.plan_id LEFT JOIN sys_plan pp ON pp.id=s.pending_plan_id WHERE s.tenant_id=? AND s.status='ACTIVE' ORDER BY s.id DESC LIMIT 1",Collections.<Object>singletonList(tenant));if(s!=null){Map<String,Object>p=requiredPlan(num(s.get("planId")));hydratePlan(p);s.put("quotaDefinitions",p.get("quotaDefinitions"));s.put("features",p.get("features"));s.put("history",db.query("SELECT pc.*,op.plan_name old_plan_name,np.plan_name new_plan_name FROM sys_tenant_plan_change pc LEFT JOIN sys_plan op ON op.id=pc.old_plan_id JOIN sys_plan np ON np.id=pc.new_plan_id WHERE pc.tenant_id=? ORDER BY pc.id DESC LIMIT 50",Collections.<Object>singletonList(tenant)));}return s;}
    private List<Map<String,Object>>overLimit(long tenant,Map<String,Object>target){Map<String,Long>usage=new LinkedHashMap<String,Long>();for(TenantQuotaContributor q:TenantContributorRegistry.quota())usage.putAll(q.currentUsage(tenant));List<Map<String,Object>>out=new ArrayList<Map<String,Object>>();for(Map<String,Object>q:db.query("SELECT quota_key,quota_limit,unlimited FROM sys_plan_quota WHERE plan_id=?",Collections.<Object>singletonList(target.get("id")))){String key=String.valueOf(q.get("quotaKey"));long used=usage.containsKey(key)?usage.get(key):0,limit=((Number)q.get("quotaLimit")).longValue();if(!"Y".equals(q.get("unlimited"))&&used>limit){Map<String,Object>x=new LinkedHashMap<String,Object>();x.put("quotaKey",key);x.put("used",used);x.put("limit",limit);out.add(x);}}return out;}
    private void activateSubscription(long tenant,long plan,Object end,String actor,String remark,Map<String,Object>old,Map<String,Object>target){db.transaction(m->{m.update("UPDATE sys_tenant_subscription SET status='REPLACED',pending_plan_id=NULL,pending_effective_time=NULL WHERE tenant_id=? AND status='ACTIVE'",Collections.<Object>singletonList(tenant));m.update("INSERT INTO sys_tenant_subscription(tenant_id,plan_id,plan_version,start_time,end_time,status,source) VALUES(?,?,?,CURRENT_TIMESTAMP,?,'ACTIVE','PLATFORM')",Arrays.<Object>asList(tenant,plan,target.get("version"),end));m.update("INSERT INTO sys_tenant_plan_change(tenant_id,old_plan_id,new_plan_id,old_plan_version,new_plan_version,changed_by,remark,effective_mode,execution_status) VALUES(?,?,?,?,?,?,?,?, 'SUCCEEDED')",Arrays.<Object>asList(tenant,old==null?null:old.get("planId"),plan,old==null?null:old.get("version"),target.get("version"),actor,remark,"IMMEDIATE"));return null;});}
    private void applyDueSubscription(long tenant){Map<String,Object>s=db.one("SELECT s.*,p.version pending_version FROM sys_tenant_subscription s JOIN sys_plan p ON p.id=s.pending_plan_id WHERE s.tenant_id=? AND s.status='ACTIVE' AND s.pending_plan_id IS NOT NULL AND s.pending_effective_time<=CURRENT_TIMESTAMP ORDER BY s.id DESC LIMIT 1",Collections.<Object>singletonList(tenant));if(s!=null)activateSubscription(tenant,num(s.get("pendingPlanId")),null,"scheduler","到期自动生效",s,requiredPlan(num(s.get("pendingPlanId"))));}

    private SecurityPrincipal principal(Context c){SecurityPrincipal p=c.attr("security.principal");if(p==null)throw new SecurityException("UNAUTHORIZED");return p;}
    private SecurityPrincipal platform(Context c,String permission){SecurityPrincipal p=principal(c);if(!provider.isAllowed(p,permission)||!provider.isAllowed(p,"platform:manage"))throw new SecurityException("PLATFORM_MANAGE_REQUIRED");return p;}
    private long tenantId(Context c){return path(c,"/system/tenant/{id}/lifecycle","id", "/system/tenant/{id}/deleteRetry","/system/tenant/{id}/deleteCancel","/system/saas/tenant/{id}/subscription","/system/saas/tenant/{id}/subscription/preview","/system/saas/tenant/{id}/subscription/pending","/system/saas/tenant/{id}/subscription/history","/system/saas/tenant/{id}/usage","/system/saas/tenant/{id}/usage/calibrate","/system/saas/tenant/{id}/quotaOverrides","/system/saas/tenant/{id}/ratePolicies","/system/saas/tenant/{id}/ratePolicy","/system/saas/tenant/{id}/rateEvents","/system/saas/tenant/{id}/rateStatistics","/system/saas/tenant/{id}/backups","/system/saas/tenant/{id}/backup","/system/saas/tenant/{id}/backup/{backupId}","/system/saas/tenant/{id}/backup/{backupId}/download","/system/saas/tenant/{id}/backup/{backupId}/restore","/system/saas/tenant/{id}/restoreTask/{taskId}","/system/saas/tenant/{id}/restoreTask/{taskId}/retry");}
    private long planId(Context c){return path(c,"/system/saas/plan/{id}","id","/system/saas/plan/{id}/copy","/system/saas/plan/{id}/publish","/system/saas/plan/{id}/status","/system/saas/plan/{id}/versions");}
    private long backupId(Context c){return path(c,"/system/saas/tenant/{id}/backup/{backupId}","backupId","/system/saas/tenant/{id}/backup/{backupId}/download","/system/saas/tenant/{id}/backup/{backupId}/restore");}
    private long taskId(Context c){return path(c,"/system/saas/tenant/{id}/restoreTask/{taskId}","taskId","/system/saas/tenant/{id}/restoreTask/{taskId}/retry");}
    private long path(Context c,String pattern,String key,String...alternatives){String value=c.pathMap(pattern).get(key);if(value==null)for(String p:alternatives){value=c.pathMap(p).get(key);if(value!=null)break;}return Long.parseLong(value);}
    @SuppressWarnings("unchecked")private Map<String,Object>body(Context c)throws Exception{return json.readValue(c.body(),Map.class);}private Map<String,Object>bodyOrEmpty(Context c)throws Exception{return c.body()==null||c.body().trim().isEmpty()?new LinkedHashMap<String,Object>():body(c);}
    private static boolean has(Context c,String key){return c.param(key)!=null&&!c.param(key).trim().isEmpty();}private static String text(Map<String,Object>b,String k){Object v=b.get(k);return v==null?"":String.valueOf(v);}private static String defaultText(Map<String,Object>b,String k,String d){String v=text(b,k);return v.trim().isEmpty()?d:v;}private static long num(Object v){return v instanceof Number?((Number)v).longValue():Long.parseLong(String.valueOf(v));}private static int intValue(Object v,int d){return v==null||String.valueOf(v).trim().isEmpty()?d:(v instanceof Number?((Number)v).intValue():Integer.parseInt(String.valueOf(v)));}private static Long nullableLimit(Object v){if(v==null||String.valueOf(v).trim().isEmpty())return null;long n=num(v);if(n<0)throw new IllegalArgumentException("限流额度不能为负数");return n;}private static BigDecimal decimal(Object v){return v==null||String.valueOf(v).trim().isEmpty()?BigDecimal.ZERO:new BigDecimal(String.valueOf(v));}private static boolean bool(Object v){return Boolean.TRUE.equals(v)||"Y".equalsIgnoreCase(String.valueOf(v))||"true".equalsIgnoreCase(String.valueOf(v));}
    private void render(Context c,Object data)throws Throwable{Map<String,Object>r=new LinkedHashMap<String,Object>();r.put("code",200);r.put("msg","操作成功");if(data!=null)r.put("data",ApiTimeFormatter.normalize(data));c.render(r);}
    private void guard(Context c,Action action)throws Throwable{try{action.run();}catch(SecurityException e){c.status(403);c.render(error(403,e.getMessage()));}catch(IllegalArgumentException e){c.status(409);c.render(error(409,e.getMessage()));}catch(Throwable e){e.printStackTrace();c.status(500);c.render(error(500,e.getMessage()==null?"系统处理失败":e.getMessage()));}}
    private static Map<String,Object>error(int code,String msg){Map<String,Object>r=new LinkedHashMap<String,Object>();r.put("code",code);r.put("msg",msg);return r;}private interface Action{void run()throws Throwable;}
}
