/**
 * 静态菜单回退结构。
 * 正常登录时以后端动态菜单为准；接口不可用时仍保持“系统管理 + AI”两模块结构。
 */
export const menuTree = [
  {
    key: "dashboard",
    title: "系统首页",
    icon: "HomeFilled",
    path: "/dashboard",
    menuType: "C",
  },
  {
    key: "system",
    title: "系统管理",
    icon: "Setting",
    menuType: "M",
    children: [
      {
        key: "system-main",
        title: "系统管理",
        icon: "Setting",
        menuType: "M",
        children: [
          {
            key: "system-user",
            path: "/system/user",
            title: "用户管理",
            icon: "User",
            routeName: "SystemUser",
            menuType: "C",
          },
          {
            key: "system-role",
            path: "/system/role",
            title: "角色管理",
            icon: "UserFilled",
            routeName: "SystemRole",
            menuType: "C",
          },
          {
            key: "system-module",
            path: "/system/module",
            title: "模块管理",
            icon: "Box",
            routeName: "SystemModule",
            menuType: "C",
          },
          {
            key: "system-menu",
            path: "/system/menu",
            title: "菜单管理",
            icon: "Menu",
            routeName: "SystemMenu",
            menuType: "C",
          },
          {
            key: "system-dept",
            path: "/system/dept",
            title: "部门管理",
            icon: "OfficeBuilding",
            routeName: "SystemDept",
            menuType: "C",
          },
          {
            key: "system-dict",
            path: "/system/dict",
            title: "字典管理",
            icon: "Collection",
            routeName: "SystemDict",
            menuType: "C",
          },
          {
            key: "system-config",
            path: "/system/config",
            title: "参数设置",
            icon: "Operation",
            routeName: "SystemConfig",
            menuType: "C",
          },
          {
            key: "system-tenant",
            path: "/system/tenant",
            title: "租户管理",
            icon: "Coin",
            routeName: "SystemTenant",
            menuType: "C",
          },
          {
            key: "system-plan",
            path: "/system/plan",
            title: "套餐管理",
            icon: "Tickets",
            routeName: "SystemPlan",
            menuType: "C",
          },
        ],
      },
      {
        key: "system-monitor",
        title: "系统监控",
        icon: "Monitor",
        menuType: "M",
        children: [
          {
            key: "monitor-operlog",
            path: "/system/monitor/operlog",
            title: "操作日志",
            icon: "Document",
            routeName: "MonitorOperlog",
            menuType: "C",
          },
          {
            key: "monitor-logininfor",
            path: "/system/monitor/logininfor",
            title: "登录日志",
            icon: "Key",
            routeName: "MonitorLogininfor",
            menuType: "C",
          },
          {
            key: "monitor-errorlog",
            path: "/system/monitor/errorlog",
            title: "错误日志",
            icon: "Warning",
            routeName: "MonitorErrorlog",
            menuType: "C",
          },
        ],
      },
      {
        key: "system-notice",
        title: "通知公告",
        icon: "Bell",
        menuType: "M",
        children: [
          {
            key: "notice-index",
            path: "/system/notice",
            title: "通知公告",
            icon: "Bell",
            routeName: "Notice",
            menuType: "C",
          },
        ],
      },
    ],
  },
  {
    key: "ai",
    title: "AI",
    icon: "Cpu",
    menuType: "M",
    children: [
      {
        key: "ai-model",
        title: "AI模型管理",
        icon: "Cpu",
        menuType: "M",
        children: [
          {
            key: "ai-model-unified",
            path: "/ai/model",
            title: "模型管理",
            icon: "Cpu",
            routeName: "AiModel",
            menuType: "C",
          },
          {
            key: "ai-provider",
            path: "/ai/provider",
            title: "模型提供商",
            icon: "Connection",
            routeName: "AiProvider",
            menuType: "C",
          },
        ],
      },
      {
        key: "ai-app",
        title: "AI应用管理",
        icon: "Box",
        menuType: "M",
        children: [
          {
            key: "ai-knowledge",
            path: "/ai/knowledge",
            title: "知识库管理",
            icon: "Reading",
            routeName: "AiKnowledge",
            menuType: "C",
          },
          {
            key: "ai-tools",
            path: "/ai/tools",
            title: "Tools管理",
            icon: "Tools",
            routeName: "AiTools",
            menuType: "C",
          },
          {
            key: "ai-skills",
            path: "/ai/skills",
            title: "Skills管理",
            icon: "MagicStick",
            routeName: "AiSkills",
            menuType: "C",
          },
          {
            key: "ai-mcp",
            path: "/ai/mcp",
            title: "MCP管理",
            icon: "Connection",
            routeName: "AiMcp",
            menuType: "C",
          },
        ],
      },
      {
        key: "ai-orchestration",
        title: "AI编排管理",
        icon: "Share",
        menuType: "M",
        children: [
          {
            key: "ai-workflow",
            path: "/ai/workflow",
            title: "Workflow工作流",
            icon: "SetUp",
            routeName: "AiWorkflow",
            menuType: "C",
          },
          {
            key: "ai-agent",
            path: "/ai/agent",
            title: "Agent智能体",
            icon: "Service",
            routeName: "AiAgent",
            menuType: "C",
          },
          {
            key: "ai-bot",
            path: "/ai/bot",
            title: "Bot聊天发布",
            icon: "ChatLineRound",
            routeName: "AiBot",
            menuType: "C",
          },
        ],
      },
    ],
  },
  {
    key: "warehouse",
    title: "数据仓库",
    icon: "DataAnalysis",
    menuType: "M",
    children: [
      {
        key: "warehouse-datasource",
        path: "/warehouse/data-source",
        title: "数据源管理",
        icon: "Connection",
        routeName: "WarehouseDataSource",
        menuType: "C",
      },
      {
        key: "warehouse-domain",
        path: "/warehouse/domain",
        title: "业务领域",
        icon: "Collection",
        routeName: "WarehouseDomain",
        menuType: "C",
      },
      {
        key: "warehouse-dimension",
        path: "/warehouse/dimension",
        title: "维度管理",
        icon: "Grid",
        routeName: "WarehouseDimension",
        menuType: "C",
      },
      {
        key: "warehouse-fact",
        path: "/warehouse/fact",
        title: "事实表管理",
        icon: "DataBoard",
        routeName: "WarehouseFact",
        menuType: "C",
      },
      {
        key: "warehouse-metric",
        path: "/warehouse/metric",
        title: "指标管理",
        icon: "TrendCharts",
        routeName: "WarehouseMetric",
        menuType: "C",
      },
      {
        key: "warehouse-dataset",
        path: "/warehouse/dataset",
        title: "数据集管理",
        icon: "Files",
        routeName: "WarehouseDataset",
        menuType: "C",
      },
    ],
  },
];
