<template><section class="exception-panel">
  <el-alert type="info" :closable="false" show-icon title="这里只显示需要人工判断的异常候选；安全候选已由系统预审，不需要逐条操作。" />
  <article class="ry-card panel-card"><div class="toolbar">
    <el-select v-model="query.category" clearable placeholder="全部异常"><el-option label="疑似重复" value="DUPLICATE"/><el-option label="内容冲突" value="CONFLICT"/><el-option label="低可信或资料不完整" value="LOW_QUALITY"/></el-select>
    <el-input v-model="query.keyword" clearable placeholder="名称或内容" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button>
  </div><div class="batch"><span>已选择 {{ selected.length }} 项</span><el-button type="danger" plain :disabled="!selected.length" @click="review(selected,'REJECT')">批量拒绝</el-button></div>
  <el-table v-loading="loading" :data="page.rows" @selection-change="selected=$event"><el-table-column type="selection" width="44"/><el-table-column label="异常类型" width="155"><template #default="{row}"><el-tag :type="row.exceptionCategory==='LOW_QUALITY'?'warning':'danger'">{{ categoryLabel(row.exceptionCategory) }}</el-tag></template></el-table-column><el-table-column prop="display_name" label="候选内容" min-width="280" show-overflow-tooltip/><el-table-column label="对象" width="80"><template #default="{row}">{{ typeLabel(row.candidate_type) }}</template></el-table-column><el-table-column label="来源" width="90"><template #default="{row}">{{row.source_count}} 个</template></el-table-column><el-table-column label="置信度" width="90"><template #default="{row}">{{Number(row.average_confidence||0).toFixed(2)}}</template></el-table-column><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><el-button link type="primary" @click="open(row)">查看证据</el-button><el-button link type="success" @click="review([row],'APPROVE')">通过</el-button><el-button v-if="row.candidate_type==='ENTITY'&&row.exceptionCategory==='DUPLICATE'" link @click="merge(row)">合并</el-button><el-button link type="danger" @click="review([row],'REJECT')">拒绝</el-button></template></el-table-column></el-table>
  <div class="pagination"><el-pagination v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :page-sizes="[10,20,50]" :total="page.total" layout="total, sizes, prev, pager, next, jumper" @change="load"/></div></article>
  <el-drawer v-model="drawer" title="异常候选与来源证据" size="min(820px,94vw)"><template v-if="detail.group"><el-descriptions :column="2" border><el-descriptions-item label="候选内容">{{detail.group.display_name}}</el-descriptions-item><el-descriptions-item label="风险">{{detail.group.risk_level}}</el-descriptions-item></el-descriptions><div v-for="m in detail.members" :key="m.id" class="evidence"><b>{{m.documentName}} · V{{m.versionNo}} · 分块 #{{m.chunkNo}}</b><p>{{m.evidence_text}}</p></div></template></el-drawer>
</section></template>
<script setup>
import { reactive, ref, watch } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { getKnowledgeGraphCandidateGroup, listKnowledgeGraphExceptions, reviewKnowledgeGraphCandidateGroups } from "@/api/ai";
const props=defineProps({knowledgeBaseId:{type:Number,required:true},documentId:Number});const loading=ref(false),drawer=ref(false),selected=ref([]),page=reactive({rows:[],total:0}),detail=reactive({group:null,members:[]}),query=reactive({category:'',documentId:props.documentId||null,keyword:'',pageNum:1,pageSize:10});
const categoryLabel=v=>({DUPLICATE:'疑似重复',CONFLICT:'内容冲突',LOW_QUALITY:'低可信或资料不完整'})[v]||v;const typeLabel=v=>({ENTITY:'实体',RELATION:'关系',FACT:'事实'})[v]||v;
async function load(){loading.value=true;try{Object.assign(page,await listKnowledgeGraphExceptions(props.knowledgeBaseId,query))}finally{loading.value=false}}function search(){query.pageNum=1;load()}function reset(){Object.assign(query,{category:'',keyword:'',pageNum:1});load()}
async function open(row){Object.assign(detail,await getKnowledgeGraphCandidateGroup(props.knowledgeBaseId,row.id));drawer.value=true}
async function review(rows,action){const strict=rows.some(x=>x.risk_level==='LOW'||x.conflict_state!=='NONE');let note='';if(strict){const r=await ElMessageBox.prompt('请填写本次异常处理说明','异常审批',{inputPattern:/.+/,inputErrorMessage:'处理说明不能为空'});note=r.value}await reviewKnowledgeGraphCandidateGroups(props.knowledgeBaseId,{ids:rows.map(x=>x.id),action,note});ElMessage.success('异常候选已处理');load()}
async function merge(row){const r=await ElMessageBox.prompt('请输入要合并到的已通过实体候选组 ID','合并重复实体',{inputPattern:/^[1-9]\d*$/,inputErrorMessage:'请输入有效 ID'});await reviewKnowledgeGraphCandidateGroups(props.knowledgeBaseId,{ids:[row.id],action:'MERGE',note:`合并至候选组 #${r.value}`,mergeTargetId:Number(r.value)});ElMessage.success('重复实体已合并');load()}
watch(()=>props.documentId,v=>{query.documentId=v||null;search()});defineExpose({refresh:load});load();
</script>
<style scoped>.exception-panel{display:grid;gap:14px}.panel-card{padding:18px}.toolbar,.batch{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:14px}.toolbar .el-select{width:200px}.toolbar .el-input{width:240px}.batch{padding:10px 12px;background:var(--el-fill-color-lighter)}.pagination{display:flex;justify-content:flex-end;margin-top:14px}.evidence{margin-top:12px;padding:14px;border:1px solid var(--el-border-color-lighter);border-radius:8px}.evidence p{white-space:pre-wrap;line-height:1.7}</style>
