<template><section class="node-manager"><article class="ry-card panel-card"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="搜索节点名称" @keyup.enter="search"/><el-select v-model="query.entityType" clearable placeholder="全部实体类型"><el-option v-for="type in entityTypes" :key="type" :label="type" :value="type"/></el-select><el-select v-model="query.status" clearable placeholder="全部状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/></el-select><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></div>
<el-table v-loading="loading" :data="page.rows"><el-table-column prop="name" label="节点" min-width="230" show-overflow-tooltip/><el-table-column prop="entityType" label="类型" width="120"/><el-table-column label="主要来源" min-width="260"><template #default="{row}"><template v-if="row.primarySource?.documentName"><b>{{row.primarySource.documentName}}</b><span class="source"> / V{{row.primarySource.versionNo}} · {{row.primarySource.evidenceCount}} 个证据</span><el-tag v-if="row.otherSourceCount" size="small" type="info">另有 {{row.otherSourceCount}} 个文件</el-tag></template><span v-else>暂无来源</span></template></el-table-column><el-table-column prop="relationCount" label="关系" width="75"/><el-table-column prop="evidenceCount" label="证据" width="75"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{row.status==='ACTIVE'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="180" fixed="right"><template #default="{row}"><el-button link type="primary" @click="$emit('view-node',row.id)">查看关系</el-button><el-button link @click="source(row)">全部来源</el-button><el-button link :type="row.status==='ACTIVE'?'danger':'success'" @click="toggle(row)">{{row.status==='ACTIVE'?'停用':'恢复'}}</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :page-sizes="[10,20,50]" :total="page.total" layout="total, sizes, prev, pager, next, jumper" @change="load"/></div></article>
<el-drawer v-model="drawer" title="节点来源" size="min(760px,94vw)"><div v-for="group in groupedSources" :key="group.documentId" class="source-group"><h4>{{group.documentName}} <el-tag v-if="group.primary" size="small">主要来源</el-tag></h4><p>V{{group.versionNo}} · {{group.items.length}} 个证据分块</p><div v-for="item in group.items" :key="item.chunkId" class="chunk">分块 #{{item.chunkNo}} · {{item.titlePath||'无标题'}}</div></div></el-drawer></section></template>
<script setup>
import { computed, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { changeKnowledgeGraphNodeStatus, getKnowledgeGraphProvenance, listKnowledgeGraphNodes } from "@/api/ai";
const props=defineProps({knowledgeBaseId:{type:Number,required:true},entityTypes:{type:Array,default:()=>[]}});defineEmits(['view-node']);const loading=ref(false),drawer=ref(false),page=reactive({rows:[],total:0}),sources=ref([]),primaryId=ref(null),query=reactive({keyword:'',entityType:'',status:'',pageNum:1,pageSize:10});
const groupedSources=computed(()=>{const map=new Map();for(const item of sources.value){if(!map.has(item.documentId))map.set(item.documentId,{documentId:item.documentId,documentName:item.documentName,versionNo:item.versionNo,primary:item.documentId===primaryId.value,items:[]});map.get(item.documentId).items.push(item)}return[...map.values()].sort((a,b)=>Number(b.primary)-Number(a.primary)||b.items.length-a.items.length)});
async function load(){loading.value=true;try{Object.assign(page,await listKnowledgeGraphNodes(props.knowledgeBaseId,query))}finally{loading.value=false}}function search(){query.pageNum=1;load()}function reset(){Object.assign(query,{keyword:'',entityType:'',status:'',pageNum:1});load()}
async function source(row){const result=await getKnowledgeGraphProvenance(props.knowledgeBaseId,{kind:'NODE',elementId:row.id});sources.value=result.sources||[];primaryId.value=row.primarySource?.documentId;drawer.value=true}
async function toggle(row){const status=row.status==='ACTIVE'?'DISABLED':'ACTIVE';await ElMessageBox.confirm(`确认${status==='ACTIVE'?'恢复':'停用'}节点“${row.name}”？`,'节点状态',{type:'warning'});await changeKnowledgeGraphNodeStatus(props.knowledgeBaseId,row.id,status);ElMessage.success('节点状态已更新');load()}
defineExpose({refresh:load});load();
</script>
<style scoped>.panel-card{padding:18px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.toolbar .el-input{width:240px}.toolbar .el-select{width:170px}.source{color:var(--ry-muted-foreground);margin-right:8px}.pagination{display:flex;justify-content:flex-end;margin-top:14px}.source-group{padding:14px;margin-bottom:12px;border:1px solid var(--el-border-color-lighter);border-radius:8px}.source-group h4{margin:0}.source-group p{color:var(--ry-muted-foreground)}.chunk{padding:7px 0;border-top:1px dashed var(--el-border-color-lighter)}</style>
